# Generated by Django 3.0.6 on 2020-06-27 22:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='educationdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('startTime', models.CharField(blank=True, default='', max_length=100)),
                ('endTime', models.CharField(blank=True, default='', max_length=100)),
                ('uni', models.CharField(blank=True, default='', max_length=100)),
                ('major', models.CharField(blank=True, default='', max_length=100)),
                ('perform', models.CharField(blank=True, default='', max_length=100)),
                ('highest', models.BooleanField(default=False)),
                ('module', models.CharField(blank=True, default='', max_length=100000)),
                ('reward', models.CharField(blank=True, default='', max_length=100000)),
                ('practice', models.CharField(blank=True, default='', max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('path', models.ImageField(blank=True, unique=True, upload_to='photos')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=100000)),
                ('description', models.CharField(blank=True, default='', max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='myArt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100000)),
                ('abstract', models.CharField(blank=True, default='', max_length=100000)),
                ('content', models.CharField(blank=True, default='', max_length=1000000)),
                ('favor', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='myTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('alias', models.CharField(blank=True, default='', max_length=100)),
                ('intro', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('degree', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('title', models.CharField(blank=True, default='', max_length=100000)),
                ('description', models.CharField(blank=True, default='', max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='theProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(blank=True, default='', max_length=100000)),
                ('title', models.CharField(blank=True, default='', max_length=100000)),
                ('description', models.CharField(blank=True, default='', max_length=100000)),
                ('role1', models.CharField(blank=True, default='', max_length=100000)),
                ('role2', models.CharField(blank=True, default='', max_length=100000)),
                ('role3', models.CharField(blank=True, default='', max_length=100000)),
                ('role4', models.CharField(blank=True, default='', max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, default='', max_length=100)),
                ('startTime', models.CharField(blank=True, default='', max_length=100)),
                ('endTime', models.CharField(blank=True, default='', max_length=100)),
                ('comp', models.CharField(blank=True, default='', max_length=100000)),
                ('roleGen', models.CharField(blank=True, default='', max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='myCom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, default='', max_length=100000)),
                ('date', models.DateTimeField(auto_now=True)),
                ('myArticle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='garden.myArt')),
            ],
        ),
        migrations.AddField(
            model_name='myart',
            name='myTag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article', to='garden.myTag'),
        ),
    ]
