# Generated by Django 3.0.6 on 2020-06-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='educationdd',
            new_name='education',
        ),
    ]
